#:kivy 1.0.9
MainScreenManager:
    Strikkeapp:

<Strikkeapp>:
    BoxLayout:
        orientation: "vertical"
        Button:
            background_color: ( 0.7, 0.4, 0, 1)
            text: "textbasert"
        Button:
            background_color: ( 0.8, 0.5, 0, 1)
            text: "Pattern basert"
        Button:
            background_color: ( 0.9, 0.6, 0, 1)
            text: "Pattern og Text basert"



